### ISSUE TITLE
Suggestion: Explain it uses IntersectionObserver API

### ISSUE THREAD

**Issue by MacKentoch** [yosbelms/react-progressive-loader#1]
Hi,

Thanks for this library 👍

May I suggest you to explain that it uses `IntersectionObserver` under the hood so that **`if`** **browser support is a concern**, suggest something like:
- [w3c IntersectionObserver polyfill](https://github.com/w3c/IntersectionObserver/tree/master/polyfill)

**Comment by yosbelms** [comment]
Hey @MacKentoch, have you reached the end of the readme? 😄 Perhaps it should be at the beginning.

**Comment by MacKentoch** [comment]
Hey @yosbelms 

Oh sorry! 

I didn't catch it 😅

Thanks and have a great day!
