### ISSUE TITLE
Preact issue

### ISSUE THREAD

**Issue by aguilera51284** [yosbelms/react-progressive-loader#10]
when i use preact i get this.

![image](https://user-images.githubusercontent.com/7749319/65112063-eec07e00-d9a3-11e9-9a58-4592d66626cd.png)

![image](https://user-images.githubusercontent.com/7749319/65112080-026be480-d9a4-11e9-86a1-e679a4287625.png)

**Comment by yosbelms** [comment]
According to https://github.com/preactjs/preact/issues/1935, it looks like something changed in `preact` or `preact-compat`. Anyway I think can be addressed in this lib by assigning `z-index` in each `Img` child. If anyone wants to take it, PRs are welcome.

**Comment by yosbelms** [comment]
@aguilera51284 Addressed in 0b3802cfaff83d459136fbcd97a6bd0ed28fb69a, please bump to 0.4.1
