### ISSUE TITLE
Additional img properties get set to surrounding div not to img

### ISSUE THREAD

**Issue by SvenChristian** [yosbelms/react-progressive-loader#4]
"This component also accepts all the img properties (className, style, ...)"

If I want to set srcSet - then the surrounding div gets this option - not the img tag for which I want to set it

**Comment by yosbelms** [comment]
Right, it doesn't work like in docs, there is some img-specific props that needs to be passed directly to the img component. One approach could be to define a property for this, eg: `imgProps` the other is to pass down certain properties. I'll take this

**Comment by yosbelms** [comment]
just published v0.3.0 now passing `srcSet`, `sizes`, and `alt` props down to the __img__ element
